### ISSUE TITLE
Groupchat messages display repeatedly 

### ISSUE THREAD

**Issue by suuuju** [confidantstation/Confidant-APP_iOS#15]
From Aug 15th, messages in the groupchat room display repeatedly, the repeating times vary from 3 to more than 10. As shown in the screenshot.
![IMG_7570](https://user-images.githubusercontent.com/54051533/63340355-6be2de00-c379-11e9-84ad-928380dc9e51.PNG)
![IMG_7571](https://user-images.githubusercontent.com/54051533/63340356-6c7b7480-c379-11e9-8a6c-cdd387740ec7.PNG)
![IMG_7572](https://user-images.githubusercontent.com/54051533/63340360-6c7b7480-c379-11e9-9086-4b8980a544a5.PNG)
![IMG_7573](https://user-images.githubusercontent.com/54051533/63340361-6c7b7480-c379-11e9-90f4-115df59019f3.PNG)
![IMG_7574](https://user-images.githubusercontent.com/54051533/63340362-6d140b00-c379-11e9-8e35-e665936637b4.PNG)

**Comment by coolc4** [comment]
这个问题是发生在哪个节点上？刚刚找了pow上没有对应得日志
希望提issue，把当时发生得版本号，附属节点等信息尽量带上，方便定位

**Comment by suuuju** [comment]
这个问题在我自己的深圳节点
Mac 1 address: 78C2C000067A 
当前所有的Confidant 版本号；V 0.3.1 (Build 106) 
 
------------------ Original ------------------

**Comment by coolc4** [comment]
解析问题发生得日志发现，当前节点的去重判定机制有问题，当网络抖动导致消息报文乱序的时候，消息去重的机制会失效
已修改，节点版本V0.1.73版本之后生效

**Comment by suuuju** [comment]
8月24日问题复现，再度重复显示。
同一节点，同一Confidant版本。

![recur_信息重复显示](https://user-images.githubusercontent.com/54051533/63662541-6b22cf80-c7f1-11e9-9dc9-7d427b41c64f.PNG)

**Comment by coolc4** [comment]
补充了解下， 这个重复的界面，是自己发的消息，然后显示就直接重复了三条？还是退出去之后，再进来拉取，显示是三条？

**Comment by suuuju** [comment]
是自己发的消息。刚发完时显示一条，退出后再进来拉取，显示3条
 
 
------------------ Original ------------------

**Comment by coolc4** [comment]
那就是群会话中把这一条消息记成三条了？对端看到的也是三条么？退出去重新拉取群聊记录，这里显示的一直也是三条？

**Comment by suuuju** [comment]
群里其他成员看到也是三条，他发了信息重复显示的截屏到群里。


 
 
------------------ Original ------------------

**Comment by coolc4** [comment]
24号的日志分析发现，是在一个超过20人的群里面，收到新的群消息，当前逻辑是接收方处理，写入数据库，发送群消息提醒，回复确认，然后app侧收到确认证明这次发送成功了，但是24号的日志就是在发送群消息提醒的时候节点程序core掉（是因为多个群推送新消息提醒任务导致程序堆栈溢出），导致程序自动重启之后，app重发消息，节点认为是新消息，重新入库导致的重复
修改方案，一，群消息推送改成集合多个推送一起发送的方式，一次群消息推送任务发送当前群所有需要推送的目标用户；二，消息确认放在群消息推送任务之前返回，不影响用户确认
V01.81版本确认修改合入，20190828升级

**Comment by suuuju** [comment]
![IMG_7847](https://user-images.githubusercontent.com/54051533/64091172-92ddde80-cd81-11e9-8d63-2bcd3298ef83.JPG)
9月2日问题复现。首次打开app 的首条信息重复三次， 其后的信息都正常显示一次。 kill掉app 重新进入群聊发信息后，显示正常。

**Comment by coolc4** [comment]
9月2号的版本，定位日志是因为群聊消息批量上报推送服务器的时候程序core dump引起的，9月4号修复升级，观察了20天，没有再出现类似情况，可以认为该问题已修复
